// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace DashboardModuleLessNamespace {
    export interface IDashboardModuleLess {
        stylesContainer: string;
    }
}

declare const DashboardModuleLessModule: DashboardModuleLessNamespace.IDashboardModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: DashboardModuleLessNamespace.IDashboardModuleLess;
};

export = DashboardModuleLessModule;
