// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace DashboardModuleScssNamespace {
    export interface IDashboardModuleScss {
        stylesHeader: string;
        stylesImage: string;
    }
}

declare const DashboardModuleScssModule: DashboardModuleScssNamespace.IDashboardModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: DashboardModuleScssNamespace.IDashboardModuleScss;
};

export = DashboardModuleScssModule;
