// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace HeaderModuleLessNamespace {
  export interface IHeaderModuleLess {
    stylesContainer: string;
    test: string;
  }
}

declare const HeaderModuleLessModule: HeaderModuleLessNamespace.IHeaderModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HeaderModuleLessNamespace.IHeaderModuleLess;
};

export = HeaderModuleLessModule;
